apiVersion: argoproj.io/v1alpha1 # Updates over time
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd # Same namespace as where argoCD is running
spec:
  project: default # every application belongs to a single project
  source:
    repoURL: https://github.com/rhiknow55/argocd-app-config
    targetRevision: HEAD # The latest commit
    path: dev
  destination:
    server: https://kubernetes.default.svc # Internal service name of k8s API server. ArgoCD can access internal endpoint, since inside (no need for external NodePort)
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true # if namespace specified in destination doesnt exist, create!

    automated: # Enable auto sync
      selfHeal: true # Override any manual changes to the k8s cluster
      prune: true # If component is renamed or service is deleted, we want argocd to do the deletion of old components
